from app.api.routes import dashboard, broadcasts, admin, ai, auth, complaints, directory, documents, evidence, guided_intake, legal_aid, notifications, tracker, women_protection, workspace, timeline, legal_tools, search, emergency, prediction, health, advocates, consultations

routers = [
    dashboard.router,
    broadcasts.router,
    auth.router,
    ai.router,
    guided_intake.router,
    legal_aid.router,
    women_protection.router,
    documents.router,
    complaints.router,
    directory.router,
    tracker.router,
    notifications.router,
    workspace.router,
    evidence.router,
    admin.router,
    timeline.router,
    legal_tools.router,
    search.router,
    emergency.router,
    prediction.router,
    health.router,
    advocates.router,
    consultations.router,
]
