"""add_consultation_broadcasts

Revision ID: 288ded1702fd
Revises: fdb35e75e9d6
Create Date: 2026-08-24 10:46:05.417960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288ded1702fd'
down_revision: Union[str, None] = 'fdb35e75e9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_broadcasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citizen_id', sa.Uuid(), nullable=False),
    sa.Column('legal_category', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('preferred_language', sa.String(length=50), nullable=False),
    sa.Column('consultation_mode', sa.String(length=20), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('preferred_date', sa.String(length=20), nullable=True),
    sa.Column('preferred_time', sa.String(length=10), nullable=True),
    sa.Column('pro_bono_requested', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_broadcasts_citizen_id'), 'consultation_broadcasts', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_consultation_broadcasts_district'), 'consultation_broadcasts', ['district'], unique=False)
    op.create_table('consultation_broadcast_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('broadcast_id', sa.Uuid(), nullable=False),
    sa.Column('advocate_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['advocate_id'], ['advocate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['broadcast_id'], ['consultation_broadcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_broadcast_recipients_advocate_id'), 'consultation_broadcast_recipients', ['advocate_id'], unique=False)
    op.create_index(op.f('ix_consultation_broadcast_recipients_broadcast_id'), 'consultation_broadcast_recipients', ['broadcast_id'], unique=False)
    op.create_table('consultation_broadcast_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('broadcast_id', sa.Uuid(), nullable=False),
    sa.Column('advocate_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('advocate_message', sa.Text(), nullable=True),
    sa.Column('proposed_fee', sa.Float(), nullable=True),
    sa.Column('consultation_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advocate_id'], ['advocate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['broadcast_id'], ['consultation_broadcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broadcast_id', 'advocate_id', name='uq_broadcast_advocate_response')
    )
    op.create_index(op.f('ix_consultation_broadcast_responses_advocate_id'), 'consultation_broadcast_responses', ['advocate_id'], unique=False)
    op.create_index(op.f('ix_consultation_broadcast_responses_broadcast_id'), 'consultation_broadcast_responses', ['broadcast_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_objects_case_number'), table_name='case_objects')
    # ### end Alembic commands ###
