"""consultation_tables

Revision ID: a261bc2c0871
Revises: 0001_initial_schema
Create Date: 2026-08-24 10:12:10.369938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.types

# revision identifiers, used by Alembic.
revision: str = 'a261bc2c0871'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advocate_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('bar_council_number', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.String(length=40), nullable=False),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.Float(), nullable=False),
    sa.Column('online_consultation', sa.Boolean(), nullable=False),
    sa.Column('offline_consultation', sa.Boolean(), nullable=False),
    sa.Column('pro_bono_available', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advocate_profiles_bar_council_number'), 'advocate_profiles', ['bar_council_number'], unique=True)
    op.create_index(op.f('ix_advocate_profiles_district'), 'advocate_profiles', ['district'], unique=False)
    op.create_index(op.f('ix_advocate_profiles_user_id'), 'advocate_profiles', ['user_id'], unique=True)
    op.create_table('advocate_availability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advocate_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('consultation_mode', sa.String(length=20), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advocate_id'], ['advocate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advocate_availability_advocate_id'), 'advocate_availability', ['advocate_id'], unique=False)
    op.create_index(op.f('ix_advocate_availability_date'), 'advocate_availability', ['date'], unique=False)
    op.create_table('consultation_appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citizen_id', sa.Uuid(), nullable=False),
    sa.Column('advocate_id', sa.Uuid(), nullable=False),
    sa.Column('availability_id', sa.Uuid(), nullable=False),
    sa.Column('legal_category', sa.String(length=120), nullable=False),
    sa.Column('case_summary', sa.Text(), nullable=False),
    sa.Column('consultation_mode', sa.String(length=20), nullable=False),
    sa.Column('appointment_date', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('consultation_fee', sa.Float(), nullable=False),
    sa.Column('meeting_details', sa.Text(), nullable=True),
    sa.Column('advocate_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advocate_id'], ['advocate_profiles.id'], ),
    sa.ForeignKeyConstraint(['availability_id'], ['advocate_availability.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_appointments_advocate_id'), 'consultation_appointments', ['advocate_id'], unique=False)
    op.create_index(op.f('ix_consultation_appointments_citizen_id'), 'consultation_appointments', ['citizen_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_appointments_citizen_id'), table_name='consultation_appointments')
    op.drop_index(op.f('ix_consultation_appointments_advocate_id'), table_name='consultation_appointments')
    op.drop_table('consultation_appointments')
    op.drop_index(op.f('ix_advocate_availability_date'), table_name='advocate_availability')
    op.drop_index(op.f('ix_advocate_availability_advocate_id'), table_name='advocate_availability')
    op.drop_table('advocate_availability')
    op.drop_index(op.f('ix_advocate_profiles_user_id'), table_name='advocate_profiles')
    op.drop_index(op.f('ix_advocate_profiles_district'), table_name='advocate_profiles')
    op.drop_index(op.f('ix_advocate_profiles_bar_council_number'), table_name='advocate_profiles')
    op.drop_table('advocate_profiles')
    # ### end Alembic commands ###
